Appintern.Web/Controllers/BackendController.cs
using Appintern.Web.DAL;
using Appintern.Web.DAL.Services;
using Appintern.Web.Library;
using Appintern.Web.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core;
using Umbraco.Core.Logging;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Core.Services;
using Umbraco.Web;
using Umbraco.Web.Composing;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedModels;
using CM = Umbraco.Web.PublishedModels;

namespace Appintern.Web.Controllers
{
    /// <summary>
    /// TELERIK APP BASED ON THE UMBRACO SITE
    /// </summary>
    public class BackendController : SurfaceController
    {
        private readonly AppinternWorksEntities db = new AppinternWorksEntities();
        private readonly Utilities utilities = new Utilities();
        private readonly ILogger _logger;

        private readonly StudentService studentService;
        private readonly GraduateService graduateService;
        private readonly SchoolService schoolService;
        private readonly EmployerService employerService;
        private readonly LiaisonOfficerService liaisonOfficerService;
        private readonly OrganizationService organizationService;
        private readonly AmbassadorService ambassadorService;
        private readonly TeacherService teacherService;
        private readonly ArticleService articleService;
        private readonly ApprenticeshipService apprenticeshipService;

        private readonly DataAccess dataAccess = new DataAccess();
        ServiceContext _serviceContext = Current.Services;

        private const string HOMEPAGE_DOCTYPE_ALIAS = "home";
        private const string APPR_LIST_DOCTYPE_ALIAS = "apprenticeshipList";
        private const string ARTICLELIST_DOCTYPE_ALIAS = "articleList";

        private const int HOME_PAGE_ID = 1080;
        private const int DASHBOARD_PAGE_ID = 1189;
        private const int APPRENTICESHIP_MAIN_PAGE_ID = 1529;
        private const int ARTICLELIST_MAIN_PAGE_ID = 1082;

        public BackendController(ILogger logger)
        {
            _logger = logger;

            studentService = new StudentService(new AppinternWorksEntities());
            graduateService = new GraduateService(new AppinternWorksEntities());
            schoolService = new SchoolService(new AppinternWorksEntities());
            employerService = new EmployerService(new AppinternWorksEntities());
            liaisonOfficerService = new LiaisonOfficerService(new AppinternWorksEntities());
            organizationService = new OrganizationService(new AppinternWorksEntities());
            ambassadorService = new AmbassadorService(new AppinternWorksEntities());
            teacherService = new TeacherService(new AppinternWorksEntities());
            articleService = new ArticleService(new AppinternWorksEntities());
            apprenticeshipService = new ApprenticeshipService(new AppinternWorksEntities());

            // Just testing to have this elsewhere in the project
            var member = Members.GetCurrentMember();

            var mail = member.GetProperty("Email").Value<string>();
        }

        protected override void Dispose(bool disposing)
        {
            studentService.Dispose();
            graduateService.Dispose();
            schoolService.Dispose();
            employerService.Dispose();
            liaisonOfficerService.Dispose();
            organizationService.Dispose();
            ambassadorService.Dispose();
            teacherService.Dispose();
            articleService.Dispose();
            apprenticeshipService.Dispose();

            base.Dispose(disposing);
        }

        private string GetBackendViewPath(string name)
        {
            return $"~/Views/Partials/Backend/{name}.cshtml";
        }

        private string GetPrintViewPath(string name)
        {
            return $"~/Views/Partials/PrintViews/{name}.cshtml";
        }

        #region DASHBOARD MAIN FUNCTIONS

        // This a telerik View outside Umbraco frame
        public ActionResult RenderDashboard()
        {
            IEnumerable<MemberCountModel> model = MemberCountBreakdown();
            return PartialView(GetBackendViewPath("_Dashboard"), model);
        }

        public ActionResult RenderDashboardHome()
        {
            return RedirectToUmbracoPage(DASHBOARD_PAGE_ID);
        }

        // Members list using Telerik Grid
        public ActionResult Members_Read([DataSourceRequest] DataSourceRequest request)
        {
            var result = utilities.GetAllMembers().OrderBy(p => p.Id);

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateUrlSLugForAllMembers()
        {
            var members = utilities.GetAllMembers1().OrderBy(p => p.Name);

            foreach (var member in members)
            {
                string memberType = member.ContentType.Alias.ToString();
                int memberId = Current.Services.MemberService.GetById(member.Id).Id;

                string urlSLug = utilities.SetUrlSlugByMemberTypeAlias(memberId, memberType);

            }
            string message = "Batch update of the UrlSlug has completed successfully.";
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region MEMBER APPRENTICESHIPS GRIDS

        // View with two grids, Members and related Apprenticeships
        public ActionResult ApprenticeshipsMembers()
        {
            //return View();
            return PartialView(GetBackendViewPath("_ApprenticeshipsMembers"));
        }

        public ActionResult Employers_Read([DataSourceRequest] DataSourceRequest request)
        {

            var data = GetMembersOfGroup("Employers");

            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ApprenticeshipsMembers_Read([DataSourceRequest] DataSourceRequest request, int employerId = 0)
        {
            var data = GetUmbracoApprenticeships(employerId);

            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        // This works
        public List<EmployersViewModel> GetMembersOfGroup(string role)
        {
            var members = _serviceContext.MemberService.GetMembersByGroup(role);

            var data = (from d in members
                        orderby d.Name
                        select new EmployersViewModel
                        {
                            MemberID = d.Id,
                            CompanyName = d.Name,
                            Email = d.Email,
                            LoginName = d.Username,
                        }).ToList();

            return data;
        }

        public List<ApprenticeshipViewModel> GetUmbracoApprenticeships(int employerId = 0)
        {
            List<ApprenticeshipViewModel> model = new List<ApprenticeshipViewModel>();

            // THESE ARE TESTED AND WORKING! //
            //IPublishedContent homePage1 = Umbraco.ContentAtRoot().Where(f => f.Name == "Home").FirstOrDefault();
            //IPublishedContent homePage = Umbraco.ContentAtRoot().Where(f => f.IsDocumentType(HOMEPAGE_DOCTYPE_ALIAS)).FirstOrDefault();
            //IPublishedContent apprenticeshipMain = homePage.Descendants().Where(x => x.IsDocumentType(APPR_LIST_DOCTYPE_ALIAS)).FirstOrDefault();
            //IEnumerable<IPublishedContent> apprenticeships1 = apprenticeshipMain.Children.OrderBy(x => x.Name);

            IPublishedContent apprenticeshipList = GetUmbracoNodeById(APPRENTICESHIP_MAIN_PAGE_ID);
            IEnumerable<IPublishedContent> apprenticeships = apprenticeshipList.Children.OrderBy(x => x.Name);

            foreach (IPublishedContent item in apprenticeships)
            {
                Employer employer = item.GetProperty("employer").GetValue() as Employer;
                if (employer.Id == employerId)
                {
                    int apprenticeshipId = item.Id;
                    string name = item.Name;
                    string title = item.GetProperty("title").GetValue().ToString();
                    string duration = item.GetProperty("duration").GetValue().ToString();
                    string commitment = item.GetProperty("commitment").GetValue().ToString();
                    string compensation = item.GetProperty("compensation").GetValue().ToString();
                    string country = item.GetProperty("country").GetValue().ToString();
                    DateTime postDate = (DateTime)item.GetProperty("postDate").GetValue();
                    DateTime startDate = (DateTime)item.GetProperty("startDate").GetValue();
                    DateTime endDate = (DateTime)item.GetProperty("endDate").GetValue();
                    string status = item.GetProperty("status").GetValue().ToString();
                    string jobSector = item.GetProperty("jobSector").GetValue().ToString();
                    string description = item.GetProperty("metaDescription").GetValue().ToString();

                    model.Add(new ApprenticeshipViewModel(apprenticeshipId, name, title, postDate, duration, commitment, compensation, jobSector, country, employerId, description, status, startDate, endDate));
                }
            }
            return model;
        }

        #endregion


        #region MEMBER ARTICLES GRIDS

        public ActionResult ArticlesMembers()
        {
            //return View();
            return PartialView(GetBackendViewPath("_ArticlesMembers"));
        }

        public ActionResult AllMembers_Read([DataSourceRequest] DataSourceRequest request)
        {
            var data = utilities.GetAllMembers().OrderBy(x => x.Type).ThenBy(x => x.Name);

            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

Appintern.Web/Views/Partials/Backend/_AmbassadorsMain.cshtml
@using Appintern.Web.ViewModels

@{
    ViewBag.Title = "Business Ambassadors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header" style="margin:5px 30px 5px 30px">
    <span style="margin:5px 30px 5px 30px;font-family:'Segoe UI';font-size:large;text-shadow:1px 1px #000000">
        <font style="color:#494949;float:left;font-family:'Segoe UI'">Business Ambassadors Data</font>
    </span>
    <span style="margin:5px 30px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px">
        @Html.ActionLink("Return to Dashboard", "RenderDashboardHome", "Backend", null, new { @class = "btn btn-warning", style = "font-size:14px" })
    </span>
    <button class="btn btn-info" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="RefreshGrid()">Refresh</button>
    <button class="btn btn-primary" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="populateEmployers()">Populate Business Ambassadors</button>
</div>

<div class="body-content" style="margin:20px 30px 5px 30px;">
    @(Html.Kendo().Grid<AmbassadorsViewModel>()
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.MemberID).Width(15).Filterable(false).Groupable(false);
            columns.Bound(c => c.FullName).Width(30).Groupable(false);
            columns.Bound(c => c.Phone).Width(20).Groupable(false);
            columns.Bound(c => c.Email).Width(20).Groupable(false);
            columns.Bound(c => c.Country).Width(20);
            columns.Bound(c => c.JobSector).Width(30).Title("Job Sector");
            columns.Bound(c => c.TaxNumber).Width(20).Groupable(false);
            columns.Bound(c => c.Employer).Width(30);
        })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .Filterable()
        .Groupable()
        .HtmlAttributes(new { style = "display: block;font-size:13px" })
        .Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.MultipleColumn))
        .Scrollable(scr => scr.Height(540))
        .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(40)
        .ServerOperation(true)
        .Model(model =>
        {
            model.Id(p => p.MemberID);
        })
        .Read(read => read.Action("AmbassadorsMain_Read", "Backend"))
        .Events(events => events.Error("error_handler"))
        )
        )
</div>


<script type="text/javascript">

    function populateEmployers() {
        $.ajax({
        url: '@Url.Action("PopulateAmbassadors", "Backend")',
        type: 'GET',
        data: "",
        contentType: 'application/json; charset=utf-8',
        success: function (data) {
            if (data != "") alert(data);
            $("#Grid").data("kendoGrid").dataSource.read();
        },
        error: function () {
            alert("Error retrieving data. Try again later.");
        }
        });
    }


    function RefreshGrid(e) {
        var grid = $("#Grid").data("kendoGrid");
        grid.dataSource.read();
    }

    function error_handler(e) {
        if (e.errors) {
            var message = "";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
        $("#Grid").data("kendoGrid").dataSource.read();
    }

</script>

Appintern.Web/Views/Partials/Backend/_ApprenticeshipsMain.cshtml
@using Appintern.Web.ViewModels

@{
    ViewBag.Title = "Apprenticeships";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header" style="margin:5px 30px 5px 30px">
    <span style="margin:5px 30px 5px 30px;font-family:'Segoe UI';font-size:large;text-shadow:1px 1px #000000">
        <font style="color:#494949;float:left;font-family:'Segoe UI'">Apprenticeships Data</font>
    </span>
    <span style="margin:5px 30px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px">
        @Html.ActionLink("Return to Dashboard", "RenderDashboardHome", "Backend", null, new { @class = "btn btn-warning", style = "font-size:14px" })
    </span>
    <button class="btn btn-info" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="RefreshGrid()">Refresh</button>
    <button class="btn btn-primary" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="populateApprenticeships()">Populate Apprenticeships</button>
</div>

<div class="body-content" style="margin:20px 30px 5px 30px;">
    @(Html.Kendo().Grid<ApprenticeshipViewModel>()
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.ApprenticeshipID).Width(15).Filterable(false).Groupable(false);
            columns.Bound(c => c.Name).Width(30).Groupable(false);
            columns.Bound(c => c.Title).Width(40).Groupable(false);
            columns.Bound(c => c.PostDate).Width(20).Format("{0:dd/MM/yyyy}").Groupable(false);
            columns.Bound(c => c.DurationMonths).Width(20).Title("Duration");
            columns.Bound(c => c.Commitment).Width(20);
            columns.Bound(c => c.Compensation).Width(25);
            columns.Bound(c => c.JobSector).Width(30).Title("Job Sectors").Groupable(false);
            columns.Bound(c => c.Status).Width(20);
            columns.Bound(c => c.Description).Width(30).Groupable(false);
            columns.Bound(c => c.Country).Width(20);
        })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .Filterable()
        .Groupable()
        .ToolBar(t => t.Search())
        .HtmlAttributes(new { style = "display: block;font-size:13px" })
        .Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.MultipleColumn))
        .Scrollable(scr => scr.Height(540))
        .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(false)
        .Model(model =>
        {
            model.Id(p => p.ApprenticeshipID);
        })
        .Read(read => read.Action("Apprenticeships_Read", "Backend"))
        .Events(events => events.Error("error_handler"))
        )
        )
</div>


<script type="text/javascript">

    function populateApprenticeships() {
        $.ajax({
        url: '@Url.Action("PopulateApprenticeships", "Backend")',
        type: 'GET',
        data: "",
        contentType: 'application/json; charset=utf-8',
        success: function (data) {
            if (data != "") alert(data);
            $("#Grid").data("kendoGrid").dataSource.read();
        },
        error: function () {
            alert("Error retrieving data. Try again later.");
        }
        });
    }


    function RefreshGrid(e) {
        var grid = $("#Grid").data("kendoGrid");
        grid.dataSource.read();
    }

    function error_handler(e) {
        if (e.errors) {
            var message = "";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
        $("#Grid").data("kendoGrid").dataSource.read();
    }

</script>

Appintern.Web/Views/Partials/Backend/_ApprenticeshipsMembers.cshtml
@using Appintern.Web.ViewModels

@{
    ViewBag.Title = "Apprenticeships";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header" style="margin:5px 30px 5px 30px">
    <span style="margin:5px 30px 5px 30px;font-family:'Segoe UI';font-size:large;text-shadow:1px 1px #000000">
        <font style="color:#494949;float:left;font-family:'Segoe UI'">Members and related apprenticeships</font>
    </span>
    <span style="margin:5px 30px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px">
        @Html.ActionLink("Return to Dashboard", "RenderDashboardHome", "Backend", null, new { @class = "btn btn-warning", style = "font-size:14px" })
    </span>
    <button class="btn btn-info" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="RefreshGrid()">Refresh</button>
</div>

<div class="body-content" style="margin:20px 30px 5px 30px;">
    @(Html.Kendo().Grid<EmployersViewModel>()
        .Name("Master")
        .Columns(columns =>
        {
            columns.Bound(c => c.MemberID).Width(20);
            columns.Bound(c => c.CompanyName).Width(50);
            columns.Bound(c => c.Email).Width(40);
            columns.Bound(c => c.LoginName).Width(30);
        })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(10))
        .Selectable()
        .Filterable()
        .HtmlAttributes(new { style = "display: block;font-size:14px" })
        .Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.MultipleColumn))
        .Scrollable(scr => scr.Height(300))
        .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(60)
        .ServerOperation(true)
        .Model(model =>
        {
            model.Id(p => p.MemberID);
        })
        .Read(read => read.Action("Employers_Read", "Backend"))
        .Events(events => events.Error("error_handler1"))
        )
        .Events(events => events.Change("change"))
        )
</div>

<div class="body-content" style="margin:20px 30px 5px 30px;">
    @(Html.Kendo().Grid<ApprenticeshipViewModel>()
        .Name("Child")
        .Columns(columns =>
        {
            columns.Bound(c => c.ApprenticeshipID).Width(15).Filterable(false);
            columns.Bound(c => c.Name).Width(20);
            columns.Bound(c => c.Title).Width(40);
            columns.Bound(c => c.PostDate).Width(20).Format("{0:dd/MM/yyyy}");
            columns.Bound(c => c.DurationMonths).Width(20).Title("Duration");
            columns.Bound(c => c.Commitment).Width(20);
            columns.Bound(c => c.Compensation).Width(25);
            columns.Bound(c => c.JobSector).Width(30).Title("Job Sectors");
            columns.Bound(c => c.Status).Width(20);
            columns.Bound(c => c.Country).Width(20);
        })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .Filterable()
        .HtmlAttributes(new { style = "display: block;font-size:14px" })
        .Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.MultipleColumn))
        .Scrollable(scr => scr.Height(240))
        .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(false)
        .Model(model =>
        {
            model.Id(p => p.ApprenticeshipID);
        })
        .Read(read => read.Action("ApprenticeshipsMembers_Read", "Backend").Data("data"))
        .Events(events => events.Error("error_handler2"))
        )
        )
</div>


<script type="text/javascript">

    function change(e) {
        var dataItem = this.dataItem(this.select());
        var employerID = dataItem.MemberID;

        $("#Child").data("kendoGrid").dataSource.read({ employerId: employerID });
        $("#Child").css("display", "block");
    }

    function data() {
        var masterGrid = $("#Master").data("kendoGrid");
        // get data item for selected row
        var dataItem = masterGrid.dataItem(masterGrid.select());
        if (dataItem) {
            return { employerId: dataItem.MemberID };
        }
        else {
            return { employerId: 0 };
        }
    }

    function RefreshGrid(e) {
        var grid = $("#Child").data("kendoGrid");
        grid.dataSource.read();
    }

    function error_handler1(e) {
        if (e.errors) {
            var message = "";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
        $("#Master").data("kendoGrid").dataSource.read();
    }

    function error_handler2(e) {
        if (e.errors) {
            var message = "";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
        $("#Child").data("kendoGrid").dataSource.read();
    }


</script>

Appintern.Web/Views/Partials/Backend/_ArticlesMain.cshtml
@using Appintern.Web.ViewModels

@{
    ViewBag.Title = "News & Events";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header" style="margin:5px 30px 5px 30px">
    <span style="margin:5px 30px 5px 30px;font-family:'Segoe UI';font-size:large;text-shadow:1px 1px #000000">
        <font style="color:#494949;float:left;font-family:'Segoe UI'">News &amp; Events Data</font>
    </span>
    <span style="margin:5px 30px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px">
        @Html.ActionLink("Return to Dashboard", "RenderDashboardHome", "Backend", null, new { @class = "btn btn-warning", style = "font-size:14px" })
    </span>
    <button class="btn btn-info" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="RefreshGrid()">Refresh</button>
    <button class="btn btn-primary" style="margin:5px 5px 5px 5px;float:right;font-family:'Segoe UI';font-size:14px" onclick="populateArticles()">Populate Articles</button>
</div>

<div class="body-content" style="margin:20px 30px 5px 30px;">
    @(Html.Kendo().Grid<ArticleViewModel>()
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.ArticleId).Width(10).Filterable(false).Groupable(false);
            columns.Bound(c => c.Name).Width(20).Groupable(false);
            columns.Bound(c => c.Title).Width(40).Groupable(false);
            columns.Bound(c => c.AuthorName).Width(30);
            columns.Bound(c => c.ArticleDate).Width(20).Format("{0:dd/MM/yyyy}").Groupable(false);
            columns.Bound(c => c.Country).Width(20);
            columns.Bound(c => c.Description).Width(70).HtmlAttributes(new { style = "font-size:12px" }).Groupable(false);
        })
        .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
        .Filterable()
        .Groupable()
        .ToolBar(t => t.Search())
        .HtmlAttributes(new { style = "display: block;font-size:14px" })
        .Sortable(sortable => sortable.AllowUnsort(true).SortMode(GridSortMode.MultipleColumn))
        .Scrollable(scr => scr.Height(540))
        .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(false)
        .Model(model =>
        {
            model.Id(p => p.ArticleId);
        })
        .Read(read => read.Action("ArticlesMain_Read", "Backend"))
        .Events(events => events.Error("error_handler"))
        )
        )
</div>


<script type="text/javascript">

    function populateArticles() {
        $.ajax({
        url: '@Url.Action("PopulateArticles", "Backend")',
        type: 'GET',
        data: "",
        contentType: 'application/json; charset=utf-8',
        success: function (data) {
            if (data != "") alert(data);
            $("#Grid").data("kendoGrid").dataSource.read();
        },
        error: function () {
            alert("Error retrieving data. Try again later.");
        }
        });

    }

    function RefreshGrid(e) {
        var grid = $("#Grid").data("kendoGrid");
        grid.dataSource.read();
    }

    function error_handler(e) {
        if (e.errors) {
            var message = "";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
        $("#Grid").data("kendoGrid").dataSource.read();
    }

</script>