Appintern.Web/Controllers/MembersController.cs
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core.Composing;
using Umbraco.Core.Persistence.Querying;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using CM = Umbraco.Web.PublishedModels;

namespace Appintern.Web.Controllers
{
    /// <summary>
    /// Source: 3 parts - this is part3 not working
    /// We have 8 different member types (Student, Graduate, Employer,...)
    /// so we need 8 route hijacking controllers.
    /// Each should be named accordingly, i.e 'StudentsController', 'GraduatesController',...
    /// The member type 'Member' is not used
    /// https://justnik.me/blog/creating-a-public-profile-page-for-members-in-umbraco-part-3
    /// </summary>
    public class MembersController :    RenderMvcController
    {
        public override ActionResult Index(ContentModel model)
        {
            return base.Index(model);
        }

        /// <summary>
        /// Route hijacking Action for member profile
        /// </summary>
        /// <param name="model"></param>
        /// <param name="memberAlias">unique Url slug for member</param>
        /// <returns>View with model</returns>
        public new ActionResult Profile(ContentModel model, string memberAlias)
        {
            var memberService = Current.Services.MemberService;
            var members = memberService.GetMembersByPropertyValue(CM.Member.GetModelPropertyType(p => p.UrlSlug).Alias, memberAlias, StringPropertyMatchType.Exact);

            if (model.Content is CM.Members membersNode && members.Count() == 1)
            {
                return View("MemberProfile", membersNode);
            }
            else
                return View("InvalidProfile", model.Content);
        }
    }
}

Appintern.Web/Controllers/ProfilesController.cs
using Appintern.Core.Services;
using Appintern.Web.Library;
using Appintern.Web.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Composing;
using Umbraco.Core.Logging;
using Umbraco.Core.Models;
using Umbraco.Core.Persistence.Querying;
using Umbraco.Core.Services;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedModels;
using CM = Umbraco.Web.PublishedModels;
using MvcPaging;
namespace Appintern.Web.Controllers
{
    public class ProfilesController : SurfaceController
    {
        private readonly Utilities utilities = new Utilities();
        private readonly ILogger _logger;
        private readonly IDataTypeValueService _dataTypeValueService;
        private readonly IMemberService _memberService;

        public ProfilesController(ILogger logger, IDataTypeValueService dataTypeValueService, IMemberService memberService)
        {
            _logger = logger;
            _dataTypeValueService = dataTypeValueService;
            _memberService = memberService;
        }

        private string GetMemberViewPath(string name)
        {
            return $"~/Views/Partials/Member/{name}.cshtml";
        }

        private string GetProfileViewPath(string name)
        {
            return $"~/Views/Partials/Profiles/{name}.cshtml";
        }

        // Need this, otherwise throws exception 'action not found'
        // Alterantively, omitting the tag defaults to both
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult RenderMemberForm(string memberAlias, string memberType)
        {
            string memberForm;

            if (memberType == "member" || memberType == "Member")
            {
                MemberProfileModel memberModel;
                memberForm = "_MemberProfile";
                memberModel = GetMemberProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), memberModel);
            }
            else if (memberType == "student")
            {
                StudentProfileModel studentModel;
                memberForm = "_StudentProfile";
                studentModel = GetStudentProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), studentModel);
            }
            else if (memberType == "graduate")
            {
                GraduateProfileModel graduateModel;
                memberForm = "_GraduateProfile";
                graduateModel = GetGraduateProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), graduateModel);
            }
            else if (memberType == "school")
            {
                SchoolProfileModel schoolModel;
                memberForm = "_SchoolProfile";
                schoolModel = GetSchoolProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), schoolModel);
            }
            else if (memberType == "teacher")
            {
                TeacherProfileModel teacherModel;
                memberForm = "_TeacherProfile";
                teacherModel = GetTeacherProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), teacherModel);
            }
            else if (memberType == "ambassador")
            {
                AmbassadorProfileModel ambassadorModel;
                memberForm = "_AmbassadorProfile";
                ambassadorModel = GetAmbassadorProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), ambassadorModel);
            }
            else if (memberType == "liaison")
            {
                LiaisonProfileModel liaisonModel;
                memberForm = "_LiaisonProfile";
                liaisonModel = GetLiaisonProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), liaisonModel);
            }
            else if (memberType == "organization")
            {
                OrganizationProfileModel organizationModel;
                memberForm = "_OrganizationProfile";
                organizationModel = GetOrganizationProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), organizationModel);
            }
            else if (memberType == "employer")
            {
                EmployerProfileModel employerModel;
                memberForm = "_EmployerProfile";
                employerModel = GetEmployerProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), employerModel);
            }
            else
            {
                MemberProfileModel memberModel;
                memberForm = "_MemberProfile";
                memberModel = GetMemberProfileModel(memberAlias);
                return PartialView(GetMemberViewPath(memberForm), memberModel);
            }
        }

        #region MEMBERS LIST & PROFILES

        public ActionResult MemberListForm()
        {
            MemberListModel model = new MemberListModel();

            model.MemberTypes = _dataTypeValueService.GetItemsFromValueListDataType("Dropdown Member Types", null);

            //model.ListResults = utilities.GetAllMembers1();
            model.ProfileResults = GetMemberProfilesByType().ToPagedList(pageIndex:0, pageSize:5);

            return PartialView(GetMemberViewPath("_MemberListForm"), model);
        }

        //HTTP POST gia to initial request. Edw fortwnei to model opws prin kai kanei to ToPagedList gia na kanei to paging
        [HttpPost]
        public ActionResult SubmitMemberListForm(MemberListModel model, int? page)
        {
            string memberType = model.MemberType;
            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;

            model.ProfileResults = GetMemberProfilesByType(memberType).ToPagedList(currentPageIndex, pageSize: 5);

            return RenderListResults(model.ProfileResults);
        }

        //HTTP GET kanei to Paging otan patas to link tou page. Edw 8eloume to type san string gia na er8ei pisw me th GET
        // kai na xsanatrexsei h GetMemberProfilesByType. 
        //Prospa8hsa me diaforous tropous na epistrefw model pisw de mou vghke an ginete teleia 8a paixsei k mono me ena action.
        [HttpGet]
        public ActionResult SubmitMemberListForm(string type, int? page)
        {
            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;

            MemberListModel model = new MemberListModel();
            model.ProfileResults = GetMemberProfilesByType(type).ToPagedList(currentPageIndex, pageSize: 5);

            return PartialView(GetMemberViewPath("_MemberListResultsGrid"), model.ProfileResults);
        }

        public ActionResult RenderListResults(IPagedList<MemberTypeProfile> model)
        {
            return PartialView(GetMemberViewPath("_MemberListResults"), model);
        }

        #endregion

        public IEnumerable<IMember> GetMemberListByType(string memberType)
        {
            if (memberType == "Business Ambassadors")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "ambassador");
            else if (memberType == "Employers")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "employer");
            else if (memberType == "Graduates")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "graduate");
            else if(memberType == "Liaison Officers")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "liaison");
            else if(memberType == "Social Partners")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "organization");
            else if (memberType == "Schools")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "school");
            else if (memberType == "Students")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "student");
            else if(memberType == "Teachers")
                return utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "teacher");
            else
                return utilities.GetAllMembers1();
        }

        public List<MemberTypeProfile> GetMemberProfilesByType(string memberType = null)
        {
            List<MemberTypeProfile> data = new List<MemberTypeProfile>();

            if (memberType == "Business Ambassadors")
            {
                var members = utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "ambassador").OrderBy(x => x.Name);
                foreach (var member in members)
                {
                    Ambassador _member = Members.GetById(member.Id) as Ambassador;
                    data.Add(new MemberTypeProfile(_member.Name, member.Email, "ambassador", _member.UrlSlug));
                }
            }
            else if (memberType == "Employers")
            {
                var members = utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "employer").OrderBy(x => x.Name);
                foreach (var member in members)
                {
                    Employer _member = Members.GetById(member.Id) as Employer;
                    data.Add(new MemberTypeProfile(_member.Name, member.Email, "employer", _member.UrlSlug));
                }
            }
            else if (memberType == "Graduates")
            {
                var members = utilities.GetAllMembers1().Where(x => x.ContentTypeAlias == "graduate").OrderBy(x => x.Name);
                foreach (var member in members)
                {
                    Graduate _member = Members.GetById(member.Id) as Graduate;
                    data.Add(new MemberTypeProfile(_member.Name, member.Email, "graduate", _member.UrlSlug));
                }
            }
            else if (memberType == "Liaison Officers")

Appintern.Web/Controllers/UserController.cs
using Appintern.Core.Helpers;
using Appintern.Core.Services;
using Appintern.Web.DAL;
using Appintern.Web.Library;
using Appintern.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Logging;
using Umbraco.Core.Models;
using Umbraco.Core.Services;
using Umbraco.Web.Mvc;
using CM = Umbraco.Web.PublishedModels;

namespace Appintern.Web.Controllers
{
    public class UserController : SurfaceController
    {
        private readonly AppinternWorksEntities db = new AppinternWorksEntities();
        private readonly Utilities utilities = new Utilities();

        private readonly ILogger _logger;
        private readonly IDataTypeValueService _dataTypeValueService;
        private readonly IMemberService _memberService;

        public UserController(ILogger logger, IDataTypeValueService dataTypeValueService, IMemberService memberService)
        {
            _logger = logger;
            _dataTypeValueService = dataTypeValueService;
            _memberService = memberService;
        }

        private string GetViewPath(string name)
        {
            return $"~/Views/Partials/Member/{name}.cshtml";
        }

        public ActionResult RenderSignUp()
        {
            // Get data source for dropdown list in the partial View
            IEnumerable<SelectListItem> categories =_dataTypeValueService.GetItemsFromValueListDataType("Dropdown Member Categories", null);

            SignUpModel model = new SignUpModel()
            {
                Name = "",
                Email = "",
                Username = "",
                Password = "",
                ConfirmPassword = "",
                MemberCategories = categories
            };

            return PartialView(GetViewPath("_MemberSignUp"), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitSignUp(SignUpModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (!MemberHelper.MemberExists(model.Email, model.Username))
                {
                    try
                    {
                        // Dropdwon item is the string value
                        string memberType = utilities.GetMemberType(model.MemberCategory);
                        string memberGroup = utilities.GetMemberGroup(model.MemberCategory);

                        int memberId = MemberHelper.CreateCustomMember(model.Username, model.Name, model.Email, model.Password, memberType, memberGroup);

                        if (memberId > 0)
                        {
                            string memberUrl = utilities.SetMemberUrlSlug(memberId, memberType);
                            return Redirect("/login/");
                        }
                        else
                            return CurrentUmbracoPage();
                    }
                    catch (Exception ex)
                    {
                        _logger.Error(typeof(UserController), ex, "Error registering new member.");
                        ModelState.AddModelError("", ex.Message);
                        return CurrentUmbracoPage();
                    }
                }
                ModelState.AddModelError("", "This email or username is already used. Registration cancelled.");
            }
            return CurrentUmbracoPage();
        }

        public ActionResult RenderLogin()
        {
            return PartialView(GetViewPath("_MemberLogin"), new LoginModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLogin(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, createPersistentCookie: true);

                    UrlHelper myHelper = new UrlHelper(HttpContext.Request.RequestContext);

                    if (myHelper.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return Redirect("~/");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "The username or password provided is incorrect.");
                }
            }
            return CurrentUmbracoPage();
        }

        public ActionResult RenderLogout()
        {
            return PartialView(GetViewPath("_MemberLogout"), null);
        }

        [HttpPost]
        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();

            return Redirect("~/");
        }


        #region UTILITIES

        public IMember GetMemberFromUser(MembershipUser user)
        {
            return user != null ? _memberService.GetByUsername(user.UserName) : null;
        }

        public bool ValidFileExtension(string extension)
        {
            string[] extensions = { "PNG", "JPEG", "JPG", "GIF", "WEBP", "TIFF" };

            List<string> valid_extensions = new List<string>(extensions);

            if (valid_extensions.Contains(extension.ToUpper()))
                return true;
            return false;
        }

        #endregion
    }
}

Appintern.Web/Views/ApprenticeshipList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using ContentModels = Umbraco.Web.PublishedModels;

@using ClientDependency.Core.Mvc
@{
    Layout = "master.cshtml";
    Html.RequiresCss(Url.Content("~/css/Article-List.css"));
    var loggedMember = Members.GetCurrentMember();
    string memberType = loggedMember != null ? loggedMember.ContentType.Alias.ToString() : "";
}

@Html.RenderCssHere()

    @if (string.IsNullOrEmpty(memberType))
    {
        Response.Redirect("~/login");
    }
    else if (memberType == "student")
    {
        Response.Redirect("~/access-error");
    }
    else
    {
        Html.RenderPartial("Partials/Content/_Apprenticeships");
    }

Appintern.Web/Views/Article.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{ 
    Layout = "Master.cshtml";
    Html.RequiresCss(Url.Content("~/css/Article-Clean.css")); 
}

@Html.RenderCssHere()

@{ Html.RenderPartial("Content/_ArticleContent"); }

Appintern.Web/Views/ArticleList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{ 
    Layout = "Master.cshtml";
    Html.RequiresCss(Url.Content("~/css/Article-List.css")); 
}

@Html.RenderCssHere()

@{ Html.RenderPartial("Partials/Content/_LatestArticles"); }

Appintern.Web/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();

    Html.RequiresCss(Url.Content("~/css/Contact-Form-Clean.css"));
    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js");
    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js");
    Html.RequiresJs(Url.Content("~/scripts/jquery.validate.min.js"));
    Html.RequiresJs(Url.Content("~/scripts/jquery.validate.unobtrusive.min.js"));
    Html.RequiresJs(Url.Content("~/scripts/jquery.unobtrusive-ajax.min.js"));
    Html.RequiresJs(Url.Content("~/scripts/contactForm.js"));
}

@Html.RenderCssHere()
@Html.RenderJsHere()

<div class="contact-clean">
    @{ Html.RenderAction("RenderTitleControls", "Content"); }

    @{ Html.RenderAction("RenderForm", "ContactSurface"); }
</div>

Appintern.Web/Views/Employment.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Employment>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
    string mainImageUrl = Model.Value<IPublishedContent>("mainImage")?.GetCropUrl(1920, 400) ?? "";
}

<style>
    .search-header {
        text-align: center;
        font-weight: 700;
        margin-top: 10px;
        color: #808080;
    }

    div.fluent-image {
        color: #fff;
        text-align: center;
        background-size: cover;
        background-position: center;
        padding-top: 0px;
        padding-bottom: 0px;
        margin-bottom: 0;
    }
</style>

<div class="col-md-12" style="margin-top:0px;margin-bottom:20px">
    <div class="fluent-image" style="background-image:url('@(mainImageUrl)');height:400px"></div>
    <h2 class="col-md-12 search-header">@(Model.Value<string>("title"))</h2>
    <h4 class="col-md-12" style="text-align:center;color:#808080">@Html.Raw(Model.Value("description"))</h4>
</div>

Appintern.Web/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc
@using Appintern.Web.Library

@{ 
    Layout = "master.cshtml";
    Html.RequiresCss(Url.Content("~/css/Article-List.css"));
    Html.RequiresCss(Url.Content("~/css/Carousel-Hero.css"));

    int nodeId = Umbraco.AssignedContentItem.Id;
    string cookieName = String.Format("PageView_{0}", nodeId);
    if (Session[cookieName] == null)
    {
        HitCounter.RecordView(nodeId);
        Session[cookieName] = 1;
    }
}

@Html.RenderCssHere()

@Html.CachedPartial("Partials/Content/_MainCarousel", Model, 3600)

<!-- Targeted section -->
@{ Html.RenderAction("RenderTargetedSection", "Content"); }

<!-- Services section -->
@{ Html.RenderAction("RenderServicesSection", "Content"); }

<!-- Latest News section -->
@Html.CachedPartial("Partials/Content/_LatestArticles", Model, 3600)

Appintern.Web/Views/InvalidProfile.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
}

<style>
    .faq-header {
        text-align: center;
        font-weight: 700;
        margin-top: 30px;
        color: #808080;
    }

    div.fluent-image {
        color: #fff;
        text-align: center;
        background-size: cover;
        background-position: center;
        padding-top: 0px;
        padding-bottom: 0px;
        margin-bottom: 0;
    }

    .inline-block-center {
        text-align: center;
    }

        .inline-block-center div {
            display: inline-block;
            text-align: left;
        }

    .flex-center {
        display: flex;
        justify-content: center;
    }
</style>

<!-- This is a static page shown in the event of an invalid member profile address -->
<div class="fluent-image" style="background-image:url('~/img/carousel.jpg');height:500px"></div>
<div class="container" style="margin-top:20px">
    <h2 class="faq-header">The requested profile is not valid!</h2>
</div>

Appintern.Web/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login>

@using ContentModels = Umbraco.Web.PublishedModels;
@using ClientDependency.Core.Mvc

@{
    Layout = "master.cshtml";

    //Html.EnableClientValidation();
    //Html.EnableUnobtrusiveJavaScript();

    Html.RequiresCss(Url.Content("~/css/Contact-Form-Clean.css"));
    //Html.RequiresJs(Url.Content("~/scripts/jquery.validate.min.js"));
    //Html.RequiresJs(Url.Content("~/scripts/jquery.validate.unobtrusive.min.js"));
    //Html.RequiresJs(Url.Content("~/scripts/jquery.unobtrusive-ajax.min.js"));
    //Html.RequiresJs(Url.Content("~/scripts/jquery.unobtrusive-ajax.min.js"));

}

@Html.RenderCssHere()

<body>

    @Html.RenderJsHere()

    <div class="contact-clean">
        @{ Html.RenderAction("RenderTitleControls", "Content"); }

        @{ Html.RenderAction("RenderLogin", "User"); }
    </div>

</body>

Appintern.Web/Views/Manage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@RenderBody()

Appintern.Web/Views/MemberBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@{
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}

@RenderBody()

Appintern.Web/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Members>

@using ContentModels = Umbraco.Web.PublishedModels;

@{
    Layout = "master.cshtml";
}

Appintern.Web/Views/MembersList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ContentModels = Umbraco.Web.PublishedModels;
@using ClientDependency.Core.Mvc

@{
    Layout = "master.cshtml";
    Html.RequiresCss(Url.Content("~/css/Contact-Form-Clean.css"));
    var imageUrl = Model.HasValue(alias: "mainImage") ? Model.Value<IPublishedContent>(alias: "mainImage").GetCropUrl(1920, 400) : null;
    var loggedMember = Members.GetCurrentMember();
    string memberType = loggedMember != null ? loggedMember.ContentType.Alias.ToString() : "";
}

@section Head
{
    <style>
        button.current {
            font-weight: 700;
        }

        .search-header {
            text-align: center;
            font-weight: 700;
            margin-top: 10px;
            color: #808080;
        }

        div.fluent-image {
            color: #fff;
            text-align: center;
            background-size: cover;
            background-position: center;
            padding-top: 0px;
            padding-bottom: 0px;
            margin-bottom: 0;
        }
    </style>
}

@Html.RenderCssHere()


<div class="col-md-12" style="margin-top:0px">
    <div class="fluent-image" style="background-image:url('@(imageUrl)');height:400px"></div>
    <h2 class="col-md-12 search-header">@(Model.Value<string>("title"))</h2>
    <h4 class="col-md-12" style="text-align:center;color:#808080">@Html.Raw(Model.Value("description"))</h4>
</div>

@{
    Html.RenderAction("MemberListForm", "Profiles");
}

@section ScriptsBottom
{
    <!--You may not want to reference jQuery here if you already have it in your master template-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive-ajax.js")"></script>

    <script type="text/javascript">

        $(document).on("click", "#submit-button", function (e) {
            e.preventDefault();
            var form = $(this).closest('form');
            $(form).submit();
        })

    </script>
}

Appintern.Web/Views/SearchApprenticeships.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "master.cshtml";
    Html.RequiresCss(Url.Content("~/css/Contact-Form-Clean.css"));
    var imageUrl = Model.HasValue(alias: "mainImage") ? Model.Value<IPublishedContent>(alias: "mainImage").GetCropUrl(1920, 400) : null;
    var loggedMember = Members.GetCurrentMember();
    string memberType = loggedMember != null ? loggedMember.ContentType.Alias.ToString() : "";
}
<style>
    button.current {
        font-weight: 700;
    }

    .search-header {
        text-align: center;
        font-weight: 700;
        margin-top: 10px;
        color: #808080;
    }

    div.fluent-image {
        color: #fff;
        text-align: center;
        background-size: cover;
        background-position: center;
        padding-top: 0px;
        padding-bottom: 0px;
        margin-bottom: 0;
    }
</style>


@Html.RenderCssHere()


<div class="col-md-12" style="margin-top:0px">
    <div class="fluent-image" style="background-image:url('@(imageUrl)');height:400px"></div>
    <h2 class="col-md-12 search-header">@(Model.Value<string>("title"))</h2>
    <h4 class="col-md-12" style="text-align:center;color:#808080">@Html.Raw(Model.Value("description"))</h4>
</div>

@if (string.IsNullOrEmpty(memberType))
{
    Response.Redirect("~/login");
}
else if (memberType == "student")
{
    Response.Redirect("~/access-error");
}
else
{
    Html.RenderAction("RenderSearch3Form", "Search", new { docTypeAliases = "apprenticeship", fieldPropertyAliases = "nodeName,title,description,metaDescription,metaName", pageSize = 6, pagingGroupSize = 3 });
}


@section ScriptsBottom
{
    <!--You may not want to reference jQuery here if you already have it in your master template-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive-ajax.js")"></script>

    <script type="text/javascript">

        function debounce(func, wait, immediate) {
            var timeout;
            return function () {
                var context = this, args = arguments;
                var later = function () {
                    timeout = null;
                    if (!immediate) func.apply(context, args);
                };
                var callNow = immediate && !timeout;
                clearTimeout(timeout);
                timeout = setTimeout(later, wait);
                if (callNow) func.apply(context, args);
            };
        }

        $(document).on("click", "#submit-button", function (e) {
            e.preventDefault();
            var form = $(this).closest('form');
            $(form).submit();
        })

        $(document).on("keyup", "#SearchTerm", debounce(function (e) {
            e.preventDefault();
            var form = $(e.target).closest('form');
            $(form).submit();
        }, 600))

    </script>
}